#!/bin/bash
#
# Inits an Advent of Code task for the specified year and day.
#
# Usage:
#   ./init-task [task]
#
# Arguments:
#   task - Optional. Format: YYYY/DD (e.g., 2025/01, 2025/12)
#          If not provided, current year and day is used.
#

set -eu

task=${1:-$(date +%Y)/$(date +%d)}
year=${task%/*}
day=${task#*/}

module="advent-of-code-$year"
filename="Day${day}"

cd "$module/src"
cp "DayX.kt" "$filename.kt"
sed -i '' "s/DayX/$filename/g" "$filename.kt"

touch "$filename.txt" "${filename}_test.txt"
git add .
